apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_user: YWljY2h5ZnNqdnRmaXlvaXJleXQ=
  db_password: amdJVlMxOTk4
  db_host: YXdzLTAtdXMtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=
